#! /bin/sh

#############################
# AUTOSTARTS                #
#############################

# load color scheme for terminal 
xrdb ~/.Xresources 

# start hotkey daemon
pgrep -x sxhkd > /dev/null || sxhkd &

# restore wallpaper
nitrogen --restore &

#############################
# DESKTOP SETUP             #
#############################

# Configuring 5 desktops on 1 monitor (main)
bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#############################
# Window Rules              #
#############################

# Rule Examples
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a st-kc-run state=floating center=true rectangle=600x590+0+140
bspc rule -a Xfce4-appfinder state=floating center=true rectangle=800x600+0+64

#############################
# POST SETUP                #
#############################

#scripts after desktops/window manager has been initiated

# start lemonbar
~/.config/lemonbar/kclemonbar.sh &

# start system tray launcher script
~/.config/trayer/start.sh &
