#! /bin/sh

#############################
# VARIABLES                 #
#############################
# adjust the prompt for this new graphical session
export PROMPT_SWITCH=1
# set the default height for my lemonbar and dmenu calls so they match
export KC_BAR_HEIGHT=20


#############################
# AUTOSTARTS                #
#############################
# Kill XFCE4 Notifications Daemon (if active) and start dunst
dunst &

# load color scheme for terminal 
xrdb ~/.Xresources 

# start hotkey daemon
pgrep -x sxhkd > /dev/null || sxhkd &

# restore wallpaper
nitrogen --restore &

# setup the screensaving daemon
xscreensaver --no-splash &

#############################
# DESKTOP SETUP             #
#############################

# Configuring 5 desktops on 1 monitor (main)
bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#############################
# Window Rules              #
#############################

# Rule Examples
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a st-kc-run state=floating center=true rectangle=600x590+0+140
bspc rule -a Xfce4-appfinder state=floating center=true rectangle=800x600+0+64
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a Pcmanfm desktop='^3' follow=on
bspc rule -a KVIrc desktop='^4' follow=on
bspc rule -a st-main desktop='^5' follow=on

#############################
# POST SETUP                #
#############################

#scripts after desktops/window manager has been initiated

# start lemonbar
~/.config/lemonbar/kclemonbar.sh &

# start system tray launcher script
~/.config/trayer/start.sh &
