#!/usr/bin/env bash

# kc-logout - gives a quick dmenu command for chosing to 
# shutdown, logout, or restart
#
# Depends on elogind

choice=$( echo -e "Shutdown\nRestart\nEnd-X" | dmenu -i -h $KC_BAR_HEIGHT -p "You're leaving? What would you like to do:" )


case "$choice" in
    "Shutdown")
        sudo /bin/shutdown -P now
        ;;
    "Restart")
        sudo /bin/shutdown -r now
        ;;
    "End-X")
        bspc quit
        ;;
    *)
        ;; # do nothing
esac

