#!/bin/env bash

# kc-windows - bash script that uses dmenu to show list of windows
# for the purpose of selecting a window to switch to.
#
# Note: Depends on xtitle

# get the list of desktop names
desktops=( $( bspc query -D --names ) )
windows=""
first_window=true
debug=false

# check to see if we are debugging
if [ ! -z "$1" ]; then
    if [[ "$1" == "debug" ]]; then
        debug=true
    fi
fi

# now iterate through each desktop building a list of all window nodes
for desktop in "${desktops[@]}"
do
    [[ "$debug" == true ]] && printf "%s\n" "(Debug) Checking windows in $desktop"
    nodes=( $(bspc query -N -n .window -d ${desktop} ) )
    [[ "$debug" == true ]] && printf "%s\n" "(Debug) [${desktop}] Pulled nodes ${nodes[@]}"

    if [[ ! -z "$nodes" ]]; then
        for node in "${nodes[@]}"
        do
            if [ $first_window = true ]; then
                first_window=false
            else 
                windows="${windows}\n" 
            fi
            windows="${windows}${desktop}: $(xtitle ${node})\t${node}"
        done
    fi
done

# make sure there are some windows
[[ -n "${windows}" ]] || exit

# get a selection, and switch based on user's input
selection=$(echo -e $windows | dmenu -i -c -bw 2 -h $KC_BAR_HEIGHT -p "Open Windows: " -l 10)

# move to selected window
bspc node "${selection}" -f
