#!/bin/env bash

# kc-windows - bash script that uses dmenu to show list of windows
# for the purpose of selecting a window to switch to.
#
# Note: Depends on xtitle

# get the list of desktop names
desktops=( $( bspc query -D --names ) )
windows=""
first_window=true

# now iterate through each desktop building a list of all window nodes
for desktop in "${desktops[@]}"
do
    nodes=( $(bspc query -N -n .window -d ${desktop} ) )
    if [[ ! -z "$nodes" ]]; then
        if [ $first_window = true ]; then
            first_window=false
        else 
            windows="${windows}\n" 
        fi

        for node in "${nodes[@]}"
        do
            windows="${windows}${desktop}: $(xtitle ${node})\t${node}"
        done
    fi
done

# make sure there are some windows
[[ -n "${windows}" ]] || exit

# get a selection, and switch based on user's input
selection=$(echo -e $windows | dmenu -i -h 28 -p "Open Windows: " -l 10)

# move to selected window
bspc node "${selection}" -f
